### ISSUE TITLE
Color Picker Issue

### ISSUE THREAD

**Issue by abn5x** [FocalPaint/FocalPaint#5]
When I pick a color, it picks it okay, but when I get to paint with the picked color, the paint on canvas is different no matter how much paint is applied or brush used.

![IMG_0290](https://user-images.githubusercontent.com/31189812/100804901-ec720480-342d-11eb-8a78-5948b8bb2dc8.jpeg)

**Comment by briend** [comment]
Thanks for reporting this!

I'm not totally sure what's happening here, but I have a hunch that you are using a couple layers here. 
I think you are painting underneath the grey "helmet" layer that is partially transparent.

If you are not using layers, then it might be the background texture affecting the paint because the paint is too "thin".  You could try increasing the `3D Volume` in the brush editor to see if that helps.  Or, you can reduce the canvas texture by going to `Layers` -> `Gears` -> `Bumpiness` slider.

I hope that helps!

**Comment by abn5x** [comment]
> Thanks for reporting this!
> 
> I'm not totally sure what's happening here, but I have a hunch that you are using a couple layers here.
> I think you are painting underneath the grey "helmet" layer that is partially transparent.
> 
> If you are not using layers, then it might be the background texture affecting the paint because the paint is too "thin". You could try increasing the `3D Volume` in the brush editor to see if that helps. Or, you can reduce the canvas texture by going to `Layers` -> `Gears` -> `Bumpiness` slider.
> 
> I hope that helps!

yes I did have two layers, if I disable the layer beneath this happens when painting:
![C3D0ACCF-FADA-4CEF-A8A9-63C2CBF6B99D](https://user-images.githubusercontent.com/31189812/100872389-08af8900-34a2-11eb-9a33-71ec30f9d464.jpeg)

Even if I delete the layer, the same bug still happens unfortunately.

**Comment by abn5x** [comment]
from what i could gather the colours always seem to be a little bit darker or desaturated then the actual picked color

**Comment by briend** [comment]
Oh wow, you found another (different?) bug I think. I never realized that a hidden layer that is below the current layer and also  less than 100% opacity would trigger this.

Thanks, I'll try to sort out both issues and let you know.

**Comment by briend** [comment]
I fixed the transparent layer issue in the latest v1.34.  I wonder if this accounts for both problem; please give it a try when you have a chance. Thanks!

**Comment by abn5x** [comment]
Hey there I was thinking that you might find helpful the source file that is giving this bug:

https://www.icloud.com/iclouddrive/08Snmhz9SB5z_Drx-eaRCEYoA#A7737244-BACD-484A-8196-CB28DF9B60BA

**Comment by abn5x** [comment]
Sadly the color picker bug still happens, though I did notice that with some colors the difference its not so big, also tried to pick and paint in a part where canvas was clean, no luck either. Also tried to "bin" the color before picking, clean the brush before painting with the picked color, no luck either. 

btw, could you please add a "dry clean"? right now the cleaning(the drop icon) is wet, meaning that after cleaning, the brush lifts up the paint before starting to put paint gradually. The "bin" color would be great to do this function, as currently for example with smudge mixers, even if I bin the color, when smudging it applies a bit of white before picking the canvas paint.

Also some settings to make the brush a round, instead of flat, and to control it only with the pressure would also be great 😊

**Comment by abn5x** [comment]
You should certainly look at the source file of the painting I sent you, as it seems to only happen in that painting, if I color pick the color from the op, and paint it in a new canvas, the picked color and painted color match perfectly, even if painted-picked-painnted another area-picked multiple times.

**Comment by briend** [comment]
> Sadly the color picker bug still happens, though I did notice that with some colors the difference its not so big, also tried to pick and paint in a part where canvas was clean, no luck either. Also tried to "bin" the color before picking, clean the brush before painting with the picked color, no luck either.

Thanks for sending that file, I was able to open it (which is great, since I've only ever opened files from my own device!) I am able to reproduce that weird color thing.  It seemed like if I did a "clean brush" THEN pick the color from the canvas, I had better luck. Definitely not ideal though!

> btw, could you please add a "dry clean"? right now the cleaning(the drop icon) is wet, meaning that after cleaning, the brush lifts up the paint before starting to put paint gradually. The "bin" color would be great to do this function, as currently for example with smudge mixers, even if I bin the color, when smudging it applies a bit of white before picking the canvas paint.

I'm actually really surprised anyone realized what that little drop icon was doing!  I think I'll add a toggle switch under than "drop icon" to enable an "auto-clean" whenever you change the brush color.  But the other issue is the "erasing" effect after cleaning the brush, which is kind of nice but I can see when that would be annoying.  I have an idea that might work.... basically set a flag to immediately saturate the smudge buffer with the canvas color (for the very first set of dabs), so that it doesn't do anything erasing... Something like that.

> 
> Also some settings to make the brush a round, instead of flat, and to control it only with the pressure would also be great 😊

I've been thinking about this too, I'll try to add a few more simple controls, but eventually I plan to add a whole Node-based editor to have a lot more flexibility. I made an issue here to track that: https://github.com/FocalPaint/FocalPaint/issues/9

**Comment by abn5x** [comment]
> I'm actually really surprised anyone realized what that little drop icon was doing! I think I'll add a toggle switch under than "drop icon" to enable an "auto-clean" whenever you change the brush color. But the other issue is the "erasing" effect after cleaning the brush, which is kind of nice but I can see when that would be annoying. I have an idea that might work.... basically set a flag to immediately saturate the smudge buffer with the canvas color (for the very first set of dabs), so that it doesn't do anything erasing... Something like that

I can see the combination of auto-clean and the flag to saturate the smudge buffer as the perfect way to describe the function to use the brush as a smudge tool (as we actually do when painting :D)

I envision the UX something like this:
- WET checkbox / DRY checkbox / Clean Button (the checkbox selection is exclusive, and affects how the Clean Button or Auto-Clean Works)
-Auto-Clean Toggle

**Comment by abn5x** [comment]
hey there, the original issue with color picking seems to be resolved now :D

**Comment by briend** [comment]
Thanks @abn5x.  Yeah I don't really know what was going on there, and not sure how it got fixed :-)
I'll leave this open for the auto-clean and instant-smudge (or whatever we're calling it) stuff

**Comment by abn5x** [comment]
> Thanks @abn5x. Yeah I don't really know what was going on there, and not sure how it got fixed :-)
> I'll leave this open for the auto-clean and instant-smudge (or whatever we're calling it) stuff

hahjahah, who knows, btw I think that it would be great if there were two types of color pickers:

- one like the current which picks the opaque “pigment” used even though the color on screen is transparent and different.

- and one which would pick the “screen color” so for example it would pick what is represented on screen taking in consideration the layers bellow and their transparency and the canvas color etc.

**Comment by briend** [comment]
Good ideas.  I’ve often tried to pick color from the wrong layer and gotten nothing.  Maybe the default picker should pull the color from the current layer, and there can be a toggle to sample Merged stack (I think that’s called sample merged).  Although, if the canvas (background) is included, the result will be opaque.  A third option could merge everything except the background, so it could set the opacity of the brush to match.  Might be funky but sounds interesting

**Comment by abn5x** [comment]
> Good ideas. I’ve often tried to pick color from the wrong layer and gotten nothing. Maybe the default picker should pull the color from the current layer, and there can be a toggle to sample Merged stack (I think that’s called sample merged). Although, if the canvas (background) is included, the result will be opaque. A third option could merge everything except the background, so it could set the opacity of the brush to match. Might be funky but sounds interesting

the current color picker already covers the "so it could set the opacity of the brush to match"you pick the picgment and then you just set the opacity that you need. The other color picker should work like the ones in most programs where it picks the color of the screen and is already opaque.

**Comment by briend** [comment]
Default is now a merged sample of all layers excluding background canvas (maybe that's a mistake).  To switch modes just double tap the picker icon
